### ISSUE TITLE
Feature request: compatibility to cardbook fields

### ISSUE THREAD

**Issue by richanl** [RealRaven2000/SmartTemplates#141]
I switched to cardbook long time ago, because TB Addressbook had many issues. 
Unfortunately SmartTemplate can only use `%from(name)%` `%from(firstname)%` `%from(mail)%` from cardbook.
This is not enough for a bit more complex tasks like creating automaticly personalized salutations as:

Guten Tag Herr Maier, or Hallo Franz or Hi Peter, or Bonjour Frédéric.

As a possible workaround, I could imagine to use `%from(nickname)%` as the field, where I write the salutation as proposed and Smarttemplate fetches this value.

**Comment by RealRaven2000** [comment]
Thanks, I did some formatting on your original request. I think pulling these values from cardbook would definitely add a lot of value to users of it. Not quite sure how you would configure the different languages / salutations (Guten Tag / Hallo / Bonjour) - the way I handle it is having different templates for different languages. I haven't found a way to automate this (selecting text depending on language) yet.

**Comment by richanl** [comment]
Example: The field `Nickname` contains the fully customized salutation for every entry in Cardbook (e.g. Hi Peter). If Smarttemplate is able to read out this field, I can generate a template, which fetches this entry as `%to(nickname)%` or `%from(nickname)%`. 
As complimentary close, I add "Freundliche Grüße/ Bien cordialement/ Kind regards" to the template. In this case, one template works (imho) perfect for all languages.

The ability to read out standard-fields of cardbook would be a great perspective for even more email-automatisation .

**Comment by RealRaven2000** [comment]
At the moment I am using the following functions in smartTemplate-overlay.js to retrieve the card from the AB and the field info from the card. I will ask Phillipe tonight (if he goes on the call) how to retrieve the card from cardbook and how it differs internally. Note that the card is retrieved by using the from/to/cc mail, so if the person has multiple identities it will just arbitrarily return the card for the first entry it encounters.

```
    function getCardFromAB(mail) {
      if (!mail) return null;
      
      let abManager = Components.classes["@mozilla.org/abmanager;1"].getService(Components.interfaces.nsIAbManager),
          allAddressBooks = []; 
          
       if (Array.isArray(abManager.directories)) {
         allAddressBooks = abManager.directories; // Tb 88
       }
       else {
         let AB = abManager.directories;
         while (AB.hasMoreElements()) {
           let addressBook = AB.getNext().QueryInterface(Components.interfaces.nsIAbDirectory);
           allAddressBooks.push(addressBook);
         }
       }
      
      // API-to-do: use API https://thunderbird-webextensions.readthedocs.io/en/latest/addressBooks.html
      for (let i=0; i<allAddressBooks.length; i++ ) {
        let addressBook = allAddressBooks[i];
        if (addressBook instanceof Components.interfaces.nsIAbDirectory) { 
          // alert ("Directory Name:" + addressBook.dirName);
          try {
            let card = addressBook.cardForEmailAddress(mail);
            if (card)
              return card;
          }
          catch(ex) {
            util.logDebug('Problem with Addressbook: ' + addressBook.dirName + '\n' + ex) ;
          }
        }
      }
      return null;
    }
```



```
    function getCardProperty(p) {
      if (!card) return '';
      let r = card.getProperty(p,"");
      if (r) {
        let d = SmartTemplate4.mimeDecoder.decode(r);
        if (d) return d;
      }
      return r;
    }
```

**Comment by CardBook** [comment]
Hi All

I like the idea ! :) you will have to use :
`let card = cardbookRepository.cardbookUtils.getCardFromEmail(email)`

and then with the card it will differ depending on the property you want...

I think that I will have to add a function for saying that CardBook is loaded...

keep me in touch to make the CardBook modifications :)

**Comment by RealRaven2000** [comment]
> I like the idea ! :) you will have to use :
> `let card = cardbookRepository.cardbookUtils.getCardFromEmail(email)`
> 
> and then with the card it will differ depending on the property you want...
> 
> I think that I will have to add a function for saying that CardBook is loaded...

Cool, for the moment I will just check for `(typeof window.cardbookRepository == "object")` to determine if it is installed and active. I think the correct way in a future proofed mx-compatible manner would be  background notification with a return value. The only problem here is that the calling function needs to be async so I have to do some architectural changes to make my whole parser function async.

**Comment by RealRaven2000** [comment]
Working on this now, let's put the comments into #50 as the main issue, going to close this one as duplicate
