### ISSUE TITLE
Feature request: template field substituted with clipboard contents

### ISSUE THREAD

**Issue by Matherion** [RealRaven2000/SmartTemplates#145]
First off - thank you for SmartTemplate4, it saves me a lot of time!

I have a feature request - it may super-specific - but it may also be easy to build, so I'll take my chances :-)

I have a workflow where I respond to student emails using a set of Smart Templates. When opening a new mail with a template, I'll have the student name and email copied onto my clipboard. It would be great if I could have it automatically inserted in the subject and email using a template field (e.g. %clipboard_as_plain_text% or something like that).

Now I manually paste this somewhere in the mail and the subject, and this would add that bit of automagic sugarcoating (and save time of course).

If this isn't easy to do, I completely understand of course - probably few people would require this, so feel free to close.

Kind regards,

Gjalt-Jorn

**Comment by RealRaven2000** [comment]
Ok, do you may not have installed the latest version (SmartTemplates 5.7) - check out the version info on the splash screen! (if you didn't see the blue buttons saying there is noew, you can open the splash screen from the information tab "About SmartTempaltes":

![image](https://user-images.githubusercontent.com/6314674/130783525-a6b22d3a-5351-45d2-95fb-345331b2652f.png)

the variable was implemented, for detail see #118. If want the clipboard feature to be expanded with more functionality (e.g. forcing plain text), I suggest you append it there!

**Comment by Matherion** [comment]
Wow, that's awesome - feature implementation _before_ a request 😬

I'm apparently running version 3.7 on Thunderbird 78.13.0, which does indeed support this, that's awesome!

I'll add comments to #118, thank you!!! 🙏

**Comment by RealRaven2000** [comment]
Implemented in 3/7 released on 20/08/2021
