### ISSUE TITLE
If no `%cursor%` is entered, HTML template may be truncated / reformatted at the end

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/SmartTemplates#149]
I have a user who had a `<table>` element as the main container which somehow was malformed by replacing the last `<td>` - a table cell - with a paragraph. Turns out this is caused by searching for a cursor `<span>` element that SmartTemplates injects at the end of the document - unless the template contains the `%cursor%` variable.

This caused the table to be malformed and the contents of the last cell being appended _after_ the table. The workaround at the moment is to insert the `%cursor%` variable within the template

**Comment by RealRaven2000** [comment]
Here is a workaround version that slightly changes the algorithm that looks for the previous element to the injected `<span class="st4cursor" />`. Instead of taking the first closing tag (`p`, `div`) or `br`, it will look for the rightmost p, div, table, br using `Max.math( )`. I was able to fix the problem with the user's specific template. It should probably be made even more universal as it only looks at these specific tags now as they are assumed to be the main "block level" elements in a template, but obviously there could be different types.

[smartTemplate-fx-3.8pre136.zip](https://github.com/RealRaven2000/SmartTemplates/files/7231245/smartTemplate-fx-3.8pre136.zip)

To test this version, download the zip file and then drag it into Thunderbird Add-ons Manager.

**Comment by macdeport** [comment]
Seems to solve the double execution of the template that was still occurring in smartTemplate-fx-3.8pre108.zip
Wait and see

**Comment by RealRaven2000** [comment]
Fixed in 3.9 / 2.17 - released on 09/12/2021
