### ISSUE TITLE
Recipient Names which are only 1 Character long are dropped

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/SmartTemplates#153]
When retrieving names from address fields, such as `%to(firstname)%` , e.g. from an email address such as j.smith@email.com the firstname "J" is dropped. This can lead to the whole variable being removed when forwarding an email using

`%to(firstname,fwd)%`

**Comment by RealRaven2000** [comment]
Test versions with bugfix:

Thunderbird 68: [smartTemplate-fx-2.17pre96.zip](https://github.com/RealRaven2000/SmartTemplates/files/7315611/smartTemplate-fx-2.17pre96.zip)
Thunderbird 78 and later: [smartTemplate-fx-3.8pre168.zip](https://github.com/RealRaven2000/SmartTemplates/files/7315612/smartTemplate-fx-3.8pre168.zip)

To try out these test versions, download the appropriate zip file and drag it into Thunderbird Add-ons Manager.

**Comment by stephankoenig** [comment]
Thank you! Did a few quick tests and everything worked!

I will report back after extensive testing.

**Comment by stephankoenig** [comment]
Tested a lot, all fine.

**Comment by RealRaven2000** [comment]
Fixed in 3.9 / 2.17 - released on 09/12/2021
