### ISSUE TITLE
Support pushing `[Esc]` to close template change confirmation

### ISSUE THREAD

**Issue by stephankoenig** [RealRaven2000/SmartTemplates#154]
When you change the template after entering text already, you get a warning. If you press escape, it should act as cancel.

![Escape](https://user-images.githubusercontent.com/1357668/137146266-ff05fec3-2b33-4b65-87d3-a4df7cdd7244.jpg)

**Comment by RealRaven2000** [comment]
Hmm, just revisitng that one right now - I did some work on the area of notificiations but have a lot more ahead. It looks like this one now unnecessarily shows some licensing info (even thought it's not a warning about licenses):

![image](https://user-images.githubusercontent.com/6314674/150382101-a47b7a5f-1c23-44b2-ab6a-36d86f9be1da.png)

First of all, I would like to remove these buttons (at least in this case) but also I can look at the ESC button again.

**Comment by stephankoenig** [comment]
Great! Thank you. 

(Unfortunately, I can not test right now, traveling. Here I have Version 68.)

**Comment by RealRaven2000** [comment]
Implemented in 3.10.1 - released on 04/Feb/2022
