### ISSUE TITLE
Font shadows in editor text field

### ISSUE THREAD

**Issue by reinerblock** [RealRaven2000/SmartTemplates#161]
As Axel already confirmed there is a font shadow definition in the respective CSS file.

`
/* editboxes for templates */

.templateBox {
    background: rgba(255, 255, 255, 0.5);
    color: #000000;
    ***text-shadow: 1px 1px 1px rgba(250, 250, 250, 0.9); /\* white shadow for dark themes \*/***
    min-height: 7em;
    font-family: consolas,"courier new",monospace;
    font-size: 9pt;
}
`

But this makes it very difficult to read the text.
Therefore please remove it completely or make it an option in the settings. :)

**Comment by RealRaven2000** [comment]
Done. See the test version below:

[smartTemplate-fx-3.8.1pre2.zip](https://github.com/RealRaven2000/SmartTemplates/files/7467113/smartTemplate-fx-3.8.1pre2.zip)

As always, to test this version, download the zip file then drag same file into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
Fixed in 3.9 - released on 09/12/2021
