### ISSUE TITLE
Text and background color from Composition settings ignored in Dark mode

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/SmartTemplates#168]
In Thunderbird's Composition settings under HTML style the user can choose not to use the default colors of the reader but configure specific colors for text and background:

![image](https://user-images.githubusercontent.com/6314674/151781945-ec899a49-2b8b-42c2-a636-a168531a9565.png)

With SmartTemplates this setting is ignored and the composer shows bright text on dark background regardless. Expected behavior would be to transfer these colors to the new template.

**Comment by RealRaven2000** [comment]
This implemented via the attributes text and bgcolor in the body element.
 
`<body text="#000000" bgcolor="#FFFFFF">`

At first glance, we could just preserve these attributes and copy them into the new body element - this may counteract any style rules that c0ouild be attached to the wanted template (imagine you  have a letter paper with yellow background) so this needs to be done in a way that can still be overwritten with CSS.

**Comment by RealRaven2000** [comment]
Without SmartTemplates, these color attributes would probably be injected by Thunderbird after the `NotifyComposeBodyReady` event. In debugger I currently do not see them when SmartTemplates executes the function `insertTemplate()`.
They are stored in global config settings under:

```
msgcompose.background_color
msgcompose.text_color
```

the easiest way would probably injecting these if the option _"Use reader's default colors"_ is inactive. This boolean flag is stored in `msgcompose.default_colors`.

**Comment by RealRaven2000** [comment]
As part of its event handler  `NotifyComposeBodyReady()`, Thunderbird calls the function `loadHTMLMsgPrefs()` to set these colors. The outer (event) function is monkey-patched by SmartTemplates and the original stored into the variable SmartTemplate4.Util.OrigNotify - which _should_ be called at some stage during Composer startup. However, when writing new messages SmartTemplates instead uses the method `NotifyComposeBodyReadyNew()` - which does _not_ call the `loadHTMLMsgPrefs()`  function. I believe the reason for omitting the `NotifyComposeBodyReady` function for new mails is the extra processing on identities which is unwanted as SmartTemplates needs to do its own stuff in order to load an identity specific template.

https://searchfox.org/comm-esr91/source/mail/components/compose/content/MsgComposeCommands.js#9071

I can probably replicate the coloring code from there.

**Comment by RealRaven2000** [comment]
For composing new messages - I added a call to Thunderbird's internal function `loadHTMLMsgPrefs()` after calling `NotifyComposeBodyReadyNew()` . This appears to fix this issue at least for writing new mails:

[smartTemplate-fx-3.10pre13.zip](https://github.com/RealRaven2000/SmartTemplates/files/7970802/smartTemplate-fx-3.10pre13.zip)

to try out this version, download the zip file, the drag it (without unpacking) into Thunderbird Add-ons manager.

**Comment by RealRaven2000** [comment]
Fixed in 3.10.1 released on 04/Feb/2022

**Comment by mattias4000** [comment]
Hello.
I still had some problems. You wrote to me earlier: "If you could add the name of the theme you are using there and include a screenshot of the forward button you click (are you using Thunderbird Conversations? Which button exactly you are using is significant. Are you using external templates from the template dropdown?) it would also be very helpful"

I add some pictures below. Hope they can be helpful:

I get wrong colours when forwarding. On New and Reply, the colours are correct.

1. The forward buttons
![smarttemplate-1 copy](https://user-images.githubusercontent.com/38947283/173362923-29820b56-8547-4af6-a50c-02c79e54a0b2.jpg)
 ...
2. The forwarded email
![smarttemplate-2 copy](https://user-images.githubusercontent.com/38947283/173362925-6620a68f-0b5c-4a32-9b59-149b911976c7.jpg)
 ..
3. The theme.
![smarttemplate-3 copy](https://user-images.githubusercontent.com/38947283/173362926-0a50347a-505d-46d3-9a5d-4e559019604e.jpg)

**Comment by RealRaven2000** [comment]
Can you force white background / black text via your forwarding template? Try to add the following lines:

```
<style>
  body {
    color: black;
    background-color: white;
  }
</style>
```

![image](https://user-images.githubusercontent.com/6314674/173373114-a130d99c-9a6a-46f3-b7de-7e0c5715b83f.png)

this is only a quick fix for the moment... but should get the job done

**Comment by mattias4000** [comment]
Hi. Adding that code makes the colors right also when forwarding. Thanks.
