### ISSUE TITLE
Make SmartTemplates compatible with Thunderbird 102 (ESR 2022/23)

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/SmartTemplates#177]
Like every year, I am planning for SmartTemplates  to be compatible with the next ESR release of Thunderbird (102)

Please add your bug reports below.

I recommend starting with beta 99 for testing, download from here:
https://www.thunderbird.net/en-US/#channel

When adding bugs below please write down the exact version of Thunderbird, expected behavior and observed behavior.

**Comment by RealRaven2000** [comment]
Quick test version from the first branch - this is based on the previous release 3.10.2

[smartTemplate-fx-3.12pre1.zip](https://github.com/RealRaven2000/SmartTemplates/files/8238278/smartTemplate-fx-3.12pre1.zip)

to install, download the zip file above and then drag into Thunderbird Add-ons Manager. 

https://github.com/RealRaven2000/SmartTemplates/tree/ESR102

To do: need to merge in latest changes from 3.11 version for Tb91.*

**Comment by RealRaven2000** [comment]
Here is a new version based on ESR91 - this includes the latest changes such as issues #170, #171, #172, #173, #174. Also modifications for the new notification box format. Max version: 99.*

[smartTemplate-fx-3.11.1pre4.zip](https://github.com/RealRaven2000/SmartTemplates/files/8316729/smartTemplate-fx-3.11.1pre4.zip)

to install, download the zip file above and then drag into Thunderbird Add-ons Manager.

**Comment by skrap** [comment]
Hello! Unfortunately the version number of thunderbird beta is now 100, which is breaking SmartTemplates again:
![image](https://user-images.githubusercontent.com/1132698/164517684-1b0c720b-b8f1-4980-bd2a-9508008e0c8d.png)

Any chance you can bump your compatibility max version up again?

**Comment by RealRaven2000** [comment]
> Hello! Unfortunately the version number of thunderbird beta is now 100, which is breaking SmartTemplates again
> Any chance you can bump your compatibility max version up again?

Of course! This one has 102.0 as max version:

[smartTemplate-fx-3.11.1pre5.zip](https://github.com/RealRaven2000/SmartTemplates/files/8535629/smartTemplate-fx-3.11.1pre5.zip)

to install, download the zip file above and then drag into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
Added issue #194 - need to patch for ComposeStartup being async.

**Comment by RealRaven2000** [comment]
New patched version at related issue: #189

**Comment by RealRaven2000** [comment]
Made a patch to fix the inconsistent indentation of menu items (with vs without icons) - in Windows 7:

before - 
![image](https://user-images.githubusercontent.com/6314674/175812366-aaabc884-94ea-471f-8328-29292617b38b.png)

after -
![image](https://user-images.githubusercontent.com/6314674/175812461-bfe5c6d2-cbcd-4e6d-8725-64ca247dd38f.png)
