### ISSUE TITLE
After FiltaQuilla filter forwards / replies with template, the next manual reply uses same template

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/SmartTemplates#205]
Related issue: https://github.com/RealRaven2000/FiltaQuilla/issues/173 reported by @[KonstabelKen](https://github.com/KonstabelKen) 

> Context: I've been using SmartTemplate for years, great addon, no issues. Recently I've started using FiltaQuilla to trigger SmartTemplate.

> Problem:
> I've encountered a bug whereby ordinary email, not an email matching a FiltaQuilla condition, is now using the SmartTemplate used by the most recent FiltaQuilla trigger.

> Circumstances:
> This is true for both replies and new (blank) mail.
> This is true across email accounts so long as the user accounts are added to same Thunderbird profile. i.e. even if the FiltaQuilla trigger is set for [user@abc.com](mailto:user@abc.com), a new mail or reply for [user@xyz.com](mailto:user@xyz.com) is opened using the last used FiltaQuilla chosen SmartTemplate.

The effect "stacks" - so if multiple Emails are forwarded / auto-replied using a Smart Template then these will trigger multiple automatic  replies (one for each manual reply)

**Comment by RealRaven2000** [comment]
This version should fix the problem - thanks to @KonstableKen for finding this! I close the related [[issue 173](https://github.com/RealRaven2000/FiltaQuilla/issues/173)]

[smartTemplate-fx-3.13pre60.zip](https://github.com/RealRaven2000/SmartTemplates/files/9234287/smartTemplate-fx-3.13pre60.zip)

To install, download the zip file and drag it into Thunderbird Add-ons manager (do not extract files).

**Comment by RealRaven2000** [comment]
Did some reformatting of the solution and added version log:

[smartTemplate-fx-3.13pre68.zip](https://github.com/RealRaven2000/SmartTemplates/files/9235810/smartTemplate-fx-3.13pre68.zip)

To install, download the zip file and drag it into Thunderbird Add-ons manager (do not extract files).

**Comment by KonstabelKen** [comment]
> This version should fix the problem - thanks to @KonstableKen for finding this! I close the related [[issue 173](https://github.com/RealRaven2000/FiltaQuilla/issues/173)]
> 
> [smartTemplate-fx-3.13pre60.zip](https://github.com/RealRaven2000/SmartTemplates/files/9234287/smartTemplate-fx-3.13pre60.zip)
> 
> To install, download the zip file and drag it into Thunderbird Add-ons manager (do not extract files).

I've been using smartTemplate-fx-3.13pre60.zip for 30 days and the problem has not resurfaced. I think you can consider your solution as robust.

Note: I have not tested smartTemplate-fx-3.13pre68.zip as I only saw it now when I came to provide feedback.

**Comment by RealRaven2000** [comment]
This change is now in 3.13 which has been released last week. Closing this issue now...

**Comment by KonstabelKen** [comment]
Just to let you know that I have re-encountered this bug.

It's just resurfaced today. It's happened on two different computers that have the same account loaded to each machine.
Both are running Thunderbird 91.11.0 (64-bit)
Both are running Smarttemplates 3.13 (I think this is the latest version)
Both are running FiltaQuilla 3.5

No changes on our end between yesterday and today that I'm aware of which might have triggered the issue again.

Have just updated FiltaQuilla to 3.6 and will let you know if the problem persists.

**Comment by RealRaven2000** [comment]
Can you make a test and console capture with the debug option `extensions.smartTemplate4.debug.fileTemplates` enabled.
Check the Debug mode box, then right-click to toggle the additional information:

![image](https://user-images.githubusercontent.com/6314674/197189018-38ac32c7-74fa-428c-b907-1c78fe41378c.png)

![image](https://user-images.githubusercontent.com/6314674/197189088-3f884122-d17c-44e9-9ef4-0204d6f8fcad.png)

In error console you will encounter messages 
"Found FileTemplate: ", `usedTemplate`, `remainingTemplateQueue`

the first  variable contains the used template, the second variable the remaining queue of templates (which should have the one just used removed). You can click either to expand and investigate.
