### ISSUE TITLE
Some Antivirus report false positives about Trojan infections. 

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/SmartTemplates#207]
If you are affected by this issue, try this replacement version:

[smartTemplate-fx-3.13pre70.zip](https://github.com/RealRaven2000/SmartTemplates/files/9275011/smartTemplate-fx-3.13pre70.zip)

to install, download the zip file - feel free to scan for viruses to make sure there are no more detections - then drag the file into Thunderbird Add-ons Manager (without unpacking it)

**Comment by goozak** [comment]
I can't whitelist files on my work computer, so I first had to delete the 'bad' `.xpi` in my profile's `extensions` folder, but everything else went without issue.  No more warnings from the antivirus!

Thanks!

**Comment by RealRaven2000** [comment]
> I can't whitelist files on my work computer, so I first had to delete the 'bad' `.xpi` in my profile's `extensions` folder, but everything else went without issue. No more warnings from the antivirus!
> 

by the way I think they whitelisted it in the meantime. "bad" is of course only because it creates a false positive due to various  properties, one of them being a similar checksum. I learned that just adding or removing comments makes this go away. Virus matching isn't exactly an exact science. If they found a real virus it would be literally blocked by all Vendors at the same time very quickly. And probably impossible to whitelist again.
