### ISSUE TITLE
Add multi language support to %spellcheck()% variable

### ISSUE THREAD

**Issue by goozak** [RealRaven2000/SmartTemplates#218]
Since TB102, it is possible to have "[Multiple active spelling dictionaries now supported in compose window](https://www.thunderbird.net/en-US/thunderbird/102.0/releasenotes/#note-14)".

It would be nice if the `%spellcheck()%` variable was updated to allow for this.

<img src="https://user-images.githubusercontent.com/454810/204095857-ba54a9b2-6927-4cd3-a9c7-c5eb76ea58a6.png" width="200" alt="Check spelling toolbar button drop-down">
<img src="https://user-images.githubusercontent.com/454810/204095868-b47fd594-f444-4c46-95a0-e9070fe5c035.png" width="400" alt="Check Spelling">

**Comment by RealRaven2000** [comment]
See issue #189 - implemented since 3.12.1 was released on 28/06/2022

**Comment by goozak** [comment]
So sorry for that.  I searched for it before posting, but clearly did a lousy job...  😕

I thought it wasn't working because I was too quick checking the drop down menu when I opened a new message.  There is a short delay before the specified languages 'kick in'.  I was just looking at the menu too soon!

**Comment by RealRaven2000** [comment]
> So sorry for that. I searched for it before posting, but clearly did a lousy job... 😕
> 
> I thought it wasn't working because I was too quick checking the drop down menu when I opened a new message. There is a short delay before the specified languages 'kick in'. I was just looking at the menu too soon!

Yeah, one of the still existing problems is that the "squiggly lines" do not always automatically disappear after loading the template that changes the language - I haven't found a way yet to force composer to "re-proof" the text on screen.

![image](https://user-images.githubusercontent.com/6314674/204796226-15056a24-7d38-47f6-8dca-09be72b144bc.png)
