### ISSUE TITLE
Template Categories containing space characters disrupt the template menus

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/SmartTemplates#222]
When we add a category that contains space characters, this will not display the contained elements and any elements following in the definition.

In error console we see the following exception:

`Uncaught DOMException: Element.querySelector: '[templateCategory=Smart Templates]' is not a valid selector`

**Comment by RealRaven2000** [comment]
So apparently the selector (based on attribute) is failing as it is misinterpreted as a descendant selector. It's a little unfortunate that it doesn't simply return no results but also throws an exception. For a discussion on the selector issue, see this [stackoverflow post](https://stackoverflow.com/questions/66771892/javascript-selector-for-element-with-attribute-with-spaces).

The fix is relatively trivial, I will wrap the category in single quotes. Here is a new test version:

[smartTemplate-fx-3.15.2pre3.zip](https://github.com/RealRaven2000/SmartTemplates/files/10360505/smartTemplate-fx-3.15.2pre3.zip)

This works with Category Names that contain spaces and even Umlauts. (I haven't tested non-standard character sets yet).

To install the version, download the zip file above and then drag the file into Thunderbird Add-ons Manager (do not extract contents).

**Comment by MarkyMarkDE** [comment]
> So apparently the selector (based on attribute) is failing as it is misinterpreted as a descendant selector. It's a little unfortunate that it doesn't simply return no results but also throws an exception. For a discussion on the selector issue, see this [stackoverflow post](https://stackoverflow.com/questions/66771892/javascript-selector-for-element-with-attribute-with-spaces).
> 
> The fix is relatively trivial, I will wrap the category in single quotes. Here is a new test version:
> 
> [smartTemplate-fx-3.15.2pre3.zip](https://github.com/RealRaven2000/SmartTemplates/files/10360505/smartTemplate-fx-3.15.2pre3.zip)
> 
> This works with Category Names that contain spaces and even Umlauts. (I haven't tested non-standard character sets yet).
> 
> To install the version, download the zip file above and then drag the file into Thunderbird Add-ons Manager (do not extract contents).

Maybe you can also replace each white-space character with %20 in the same way as thunderbird do (or I'm wrong?).

**Comment by RealRaven2000** [comment]
Fixed in version 3.16 published on 6th or March 2023
