### ISSUE TITLE
Avoid error when smartTemplates.json file does not exist

### ISSUE THREAD

**Issue by MarkyMarkDE** [RealRaven2000/SmartTemplates#227]
to prevent such error logs, it will be helpful, when we add a default file with minimal definitions or if possible an empty file, so that this errorlogs will stop.

`Feb 19 13:41:19 newcomer01-MS-7A40 thunderbird.desktop[11873]: console.log: "SmartTemplates 13:41:19.236  [2 ms]\t \n" "readStringFile() - Failure: Unix error 2 during operation open on file /home/newcomer01/.thunderbird/Marc/extensions/smartTemplates.json (Datei oder Verzeichnis nicht gefunden)"`

Alternatively, we can add as default some html "easy snippets".

**Comment by RealRaven2000** [comment]
> to prevent such error logs, it will be helpful, when we add a default file with minimal definitions or if possible an empty file, so that this errorlogs will stop.

yes I agree, it's an old "lazyness" bug. I can suppress it.

> 
> Alternatively, we can add as default some html "easy snippets".

I do like the idea, I may have enough to make up a few examples. but localisation is difficult at the moment it is "just a file" which somehow would have to be copied to the extensions folder. This may not be possible in future versions of Thunderbird. Check out 111.b2 they have the new UX "SuperNova" enabled and currently do not even support combined dropdown buttons (for selecting templates).

**Comment by RealRaven2000** [comment]
> to prevent such error logs, it will be helpful, when we add a default file with minimal definitions or if possible an empty file, so that this errorlogs will stop.

Can you disable debug mode?

**Comment by MarkyMarkDE** [comment]
> > to prevent such error logs, it will be helpful, when we add a default file with minimal definitions or if possible an empty file, so that this errorlogs will stop.
> 
> Can you disable debug mode? I think this nnly shows if you enable SmartTemplates debug mode which adds a lot of additional messages anyway.

sure i can disable smarttemplate's debug mode, and you think, that this error messages will not show up after that?

>> I do like the idea, I may have enough to make up a few examples. but localisation is difficult at the moment it is "just a file" which somehow would have to be copied to the extensions folder. This may not be possible in future versions of Thunderbird. Check out 111.b2 they have the new UX "SuperNova" enabled and currently do not even support combined dropdown buttons (for selecting templates).

oha! That's not fine.
I have just created an empty .json file, but then comes up a javascript error box (couldn't pare or something).

**Comment by RealRaven2000** [comment]
Yeah you can just add any html file to snippets here, that will remove the error:

![image](https://user-images.githubusercontent.com/6314674/222921035-95e0cc94-dc37-49b7-884f-5206a30a87db.png)

E.g. this script adds a drop shadow to a image you have selected:

`<div style="border: 1px solid rgba(80, 80, 80, 0.3); box-shadow: rgba(80, 80, 80, 0.3) 5px 5px 5px; width:max-content;">*selection*</div>`

**Comment by RealRaven2000** [comment]
And this is an example for a yellow text marker (highlights the selected text):

`<span class="highlight" style="background-color: rgba(255,255,102,0.9); padding: 1px 5px; border-radius: 7px 2px 7px 2px">*selection*</span>`

**Comment by MarkyMarkDE** [comment]
> Yeah you can just add any html file to snippets here, that will remove the error:
> 
> ![image](https://user-images.githubusercontent.com/6314674/222921035-95e0cc94-dc37-49b7-884f-5206a30a87db.png)
> 
> E.g. this script adds a drop shadow to a image you have selected:
> 
> `<div style="border: 1px solid rgba(80, 80, 80, 0.3); box-shadow: rgba(80, 80, 80, 0.3) 5px 5px 5px; width:max-content;">*selection*</div>`

sure i can, but you can it even better, this is my "lazyness" :twink:

**Comment by RealRaven2000** [comment]
> > Yeah you can just add any html file to snippets here, that will remove the error:
> > `<div style="border: 1px solid rgba(80, 80, 80, 0.3); box-shadow: rgba(80, 80, 80, 0.3) 5px 5px 5px; width:max-content;">*selection*</div>`
> 
> sure i can, but you can it even better, this is my "lazyness" :twink:

not sure if I can (creating the file is the hard thing) but I was thinking of adding snippets to the "Examples" tab for a while. But yeah. having some useful, instant examples in the Snippets menu would be quite nice. Also, when we have a lot of templates in there is can get confusing (A category filters would be great). The thing is, I will have to rewrite all the options into HTML for Tb115 first, xul is pretty much on the way out. That's going to be a huge task. 

If the pattern of adding a dropdown to an existing button (e.g. to reply) is taken away in 115 I will have to make my own reply buttons, so even more work there; I would like to keep the old possibility of clicking either reply once or selecting a template for the drop down, but that may not be possible in a future version of Thunderbird. Which means You would always have to select the default template (or no template) from the dropdown or have a second button for "normal replying". They all it a "simplification". 

Oh: and Thunderbird will not support us adding the new buttons, the user will have to do it.

I witnessed Philippe rewriting his Cardbook dialogs in HTML that was also a very large change set.

**Comment by RealRaven2000** [comment]
Here is an example for a smartTemplates.json. it points to 3 files. but they are on my hard drive not on yours:

```json
{
  "templatesNew": [
  ],
  "templatesRsp": [
  ],
  "templatesFwd": [
  ],
  "snippets": [
    {
      "path": "N:\\Mail Profiles\\a19872312.axel\\stationery\\snippets\\screenshot numbering.html",
      "label": "Screenshot Numbers",
      "category": "Layout"
    },
    {
      "path": "N:\\Mail Profiles\\a19872312.axel\\stationery\\snippets\\Shadow-box.html",
      "label": "Shadow box",
      "category": "Layout"
    },
    {
      "path": "N:\\Mail Profiles\\a19872312.axel\\stationery\\snippets\\yellow-highlighter.html",
      "label": "Yellow Marker",
      "category": "Layout"
    }
  ]
}

```

the 3 snippet template files are below - but you will have to modify the "path" variables according to where you store them. That's not something the Add-on can do for you:

[snippets.zip](https://github.com/RealRaven2000/SmartTemplates/files/10889320/snippets.zip)

**Comment by RealRaven2000** [comment]
How could this be made easier for users without losing the mechanism (all templates are stored as HTML files in arbitrary positions) - an "import snippet" function would be great but the user would have to select a location (on their local storage) in order to save it as a file. SmartTemplate could then create and fill in the menu item under Smart Snippets. 

Not sure if that would make you actually use the feature though, so is it a wasted effort?

**Comment by MarkyMarkDE** [comment]
> How could this be made easier for users without losing the mechanism (all templates are stored as HTML files in arbitrary positions) - an "import snippet" function would be great but the user would have to select a location (on their local storage) in order to save it as a file. SmartTemplate could then create and fill in the menu item under Smart Snippets.
> 
> Not sure if that would make you actually use the feature though, so is it a wasted effort?

if possible we can create by default a new folder in MAILPATH (where the extension folder is current located) and in this folder we store all smartTemplates files as default.

Alternatively, we use the extension folder.

**Comment by RealRaven2000** [comment]
I just got a report that in the new version of Thunderbird, SmartTemplates fails reading with a messagebox, that's obviously significant. I have made a fix for the new version (Thunderbird 115). 

[smartTemplate-fx-4.0pre259.zip](https://github.com/RealRaven2000/SmartTemplates/files/12027101/smartTemplate-fx-4.0pre259.zip)

This fixed version will just return an empty dataset if the file is missing (no errors displayed, and all menus will populate as expected, just without any templates). You can then add templates via the "configure menu items..." command to create the file as expected:

![image](https://github.com/RealRaven2000/SmartTemplates/assets/6314674/39468e22-6777-4ffe-882e-5df5f1e2b7d7)


I will release the second beta 4.0b2 shortly, which includes this fix.

Installation: download zip file. drag zip file into Thunderbird Add-ons Manager.

**Comment by RealRaven2000** [comment]
implemrnted in 3.18 - released 24/09/2023
