### ISSUE TITLE
Make Follow Up button above email preview less obtrusive

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/SmartTemplates#254]
At the moment the header button for replying / forwarding via external templates takes a lot of space.

![image](https://github.com/RealRaven2000/SmartTemplates/assets/6314674/48b3a863-8ffa-44a3-9ef2-b58d127c5906)

There is currently no way to remove it or move it to the overflow button [More ⯆] via an API call. 

Therefore I raised [Bug 1851172](https://bugzil.la/1851172). In the meantime I will shorten the label to only read "SmartTemplates"

**Comment by RealRaven2000** [comment]
To alleviate the problem, I made 2 changes:

1 - I shortened the label to "SmartTemplates"
2 - I added an option to hide the text in the "icon+text" mode; you can simply check the new option "hide label" on the bottom of the menu like this:

![image](https://github.com/RealRaven2000/SmartTemplates/assets/6314674/00fc47fd-0821-4a6e-8633-a7569a0fed3d)

then, in icon+text mode, there will be only the icon shown, which should be less disruptive for users who don't want to use this button. This is a workaround until there is a way to hide the button permanently using the API or Thunderbird Core UI.

![image](https://github.com/RealRaven2000/SmartTemplates/assets/6314674/40fcbcce-53ea-44b0-9f76-9e6a2fb4246f)

Preview version here:

[smartTemplate-fx-4.1.1pre18.zip](https://github.com/RealRaven2000/SmartTemplates/files/12601220/smartTemplate-fx-4.1.1pre18.zip)

------

To install in Thunderbird, download the zip file above, then drag the file into Thunderbird Add-ons Manager. Do not extract the files inside or it will not install!

**Comment by RealRaven2000** [comment]
One more version. I forgot to hide the command "Hide Label" when the button is in "Text only" mode. In that case of course it makes no sense to not show the label text because we will then add up with an empty button (no icon, no text!)

To see the change, you may have to restart Thunderbird, as it caches style sheets, just like Firefox.

[smartTemplate-fx-4.1.1pre19.zip](https://github.com/RealRaven2000/SmartTemplates/files/12601312/smartTemplate-fx-4.1.1pre19.zip)

----

To install this in Thunderbird, download the zip file above, then drag the file into Thunderbird Add-ons Manager. Do not extract the files inside or it will not install!

**Comment by JoeWinograd** [comment]
I tested the pre19 update with 115.2.2 (64-bit) on W10 Pro 22H2. It installed perfectly and worked perfectly! The shortened button text is a nice improvement. I tested it with all three Button Style settings: only **Icons**, only **Text**, both **Icons and Text**. With only-**Text** and only-**Icons**, the **Hide Label** menu pick correctly does **not** appear. With the **Icons and Text** setting, the **Hide Label** menu pick does appear and works correctly both checked and unchecked. Great job on the workaround! Regards, Joe

**Comment by RealRaven2000** [comment]
Ok, I will translate and land this in the next official version! Will close the issue once it is published to addons.thunderbird.net

**Comment by JoeWinograd** [comment]
Excellent! Very much appreciated!

**Comment by RealRaven2000** [comment]
Implemented in 4.2.1, published 25/09/2023
