### ISSUE TITLE
Template Area cut off in 115.2.3 Linux after expanding settings dialog

### ISSUE THREAD

**Issue by MarkyMarkDE** [RealRaven2000/SmartTemplates#258]
I have found an glitch in TB 115.2.3 in Linux (Ubuntu 22.04.3 64bit) with ST 4.1.
See here

![Bildschirmfoto vom 2023-09-25 12-49-37](https://github.com/RealRaven2000/SmartTemplates/assets/12845477/4da18693-e975-4784-ad39-349653a17639)

then i expand the "extras" area

![Bildschirmfoto vom 2023-09-25 12-49-44](https://github.com/RealRaven2000/SmartTemplates/assets/12845477/57bb89b2-eacb-41e3-b1b5-bee7300ad9ec)

see whats happend with the left side of the window

when i collapse the extras area you see it like my first screenshot again.

From now, I can support st4 again, Ubuntu need really long time before you get new TB versions. The 115.* I got before a few days and after 2 days the next patch for the same version.

@RealRaven2000: i follow up your answers to our users, when you think that the options for html things (Use HTML and the &lt;br&gt; thing) below the left side text area are not the best, then kick them off, and we got some space again.

**Comment by RealRaven2000** [comment]
I will try and address the issue with some workaround, but overall we need to work on completely rewriting settings in HTML.

I have created issue #259 to handle this work, will also mention it on the Tb115 compatibility issue.

**Comment by MarkyMarkDE** [comment]
> I will try and address the issue with some workaround, but overall we need to work on completely rewriting settings in HTML.
> 
> I have created issue #259 to handle this work, will also mention it on the Tb115 compatibility issue.

okay

**Comment by richanl** [comment]
I can confirm this behaviour. If you pick the corner and maximize the window,  the OK-Button appears. It's a bug, but sind I do not play around with the settings permanently, I can handle it with this "fix".

**Comment by RealRaven2000** [comment]
This problem should be now permanently addressed in the new html version of the settings dialog - see #259 - the templates page should always be readable especially with screen sizes > 600px height, >800px width:

![image](https://github.com/user-attachments/assets/e3a0f9b1-b103-4126-abfc-4943160c24f2)

Smaller sizes will contract in space and remove labels, but also add a vertical scrollbar, just in case:

![image](https://github.com/user-attachments/assets/b9f5f90f-1ff5-472b-881c-dc55deffb534)
