### ISSUE TITLE
KI in Thunderbird?

### ISSUE THREAD

**Issue by Peter300875** [RealRaven2000/SmartTemplates#260]
Dear all,
I'm not sure if I'm in the right forum here. If not, please let me know.

I use Peter Krueckel's software “[https://pitrium.de/sprach_zu_text”](https://pitrium.de/sprach_zu_text%E2%80%9D) to translate MP3 that I receive by email into text.
Is there a way to integrate “Widerporst” into Thunderbird so that I can see the text in the email?

Or is there already an extension to convert speech to text in thunderbird?

Best regards
Peter

**Comment by RealRaven2000** [comment]
SOrry this isn't the right place to ask the question - this github is for the Add-on [SmartTemplates](https://addons.thunderbird.net/en-US/thunderbird/addon/smarttemplate4/).

Please check out the [Thunderbird support pages](https://support.mozilla.org/en-US/products/thunderbird).
