### ISSUE TITLE
double registration same e-mail

### ISSUE THREAD

**Issue by Luigi23465234** [RealRaven2000/SmartTemplates#281]
can i have support? tnx

**Comment by RealRaven2000** [comment]
Sure  i can cancel one, please send me an email using the support tab. If you have an order number (starting with QUI) this would help.

**Comment by Luigi23465234** [comment]
Dear, let's solve the problem. Tnx

**Comment by RealRaven2000** [comment]
> Dear, let's solve the problem. Tnx

have you sent me the email yet? I do not know your real name or email address so how am I supposed to find the license?

Alternatively give me one of the order numbers (they start with QUI- )

**Comment by Luigi23465234** [comment]
Sorry I haven't understood, now I send the e-mail about QUI240311-4310-36204

Thank you so much!

**Comment by Luigi23465234** [comment]
news?

**Comment by RealRaven2000** [comment]
> news?

I am not sure I received anything from yourself in the meantime but I am resending you the license now to your **_admin_** address at _**printimm.it**_ . Sorry I have to give the detail here in this public issue but I don't think you reached out to me directly / privately. 

Please make sure that you whitelist my sender address `axel[dot]grude[at]gmail[dot]com` .

**Comment by RealRaven2000** [comment]
closing as RESOLVED - not sure if the person got in touch via email, hope it worked out otherwise they can reach out again
