### ISSUE TITLE
New "Edit template" Button in file templates - to open template in user defined editor

### ISSUE THREAD

**Issue by RealRaven2000** [RealRaven2000/SmartTemplates#282]
In order to streamline quick editing of external templates, the configuration editor in SmartTemplates should have a button to open an (external) editor to edit the HTML. The user should be able to determine (with a setting) which external program would be used to edit the template. A good space to put this in the UI is in the toolbar below the list of templates:

![image](https://github.com/RealRaven2000/SmartTemplates/assets/6314674/0fa22be8-49eb-4140-9977-f0cdf21b2b66)

(beside that we could add a settings wheel which could also lead to more settings that influence templates)

**Comment by AlbertHain** [comment]
would be a great feature - editing a config manualy gives a greater overview and would be faster when several changes have to be made.

**Comment by RealRaven2000** [comment]
Here is a test version:

![image](https://github.com/RealRaven2000/SmartTemplates/assets/6314674/7789a35b-67b5-4cbc-b674-2646ae0c1643)

when used for the first time it prompts the user to add the path to the editor into a configuration window, hopefully the explanations are clear enough (fully localised in this version).

[smartTemplate-fx-4.5pre24.zip](https://github.com/RealRaven2000/SmartTemplates/files/15051725/smartTemplate-fx-4.5pre24.zip)

-------

To try out the version above download the zip file and drag the file into Thunderbird Add-ons Manager (do not extract contents, it won't install like that)

**Comment by AlbertHain** [comment]
thanks, great, makes editing templates **a lot** easier :-)

**Comment by RealRaven2000** [comment]
Implemented in 4.5 released on 14/05/2024
