### ISSUE TITLE
TB 128 ESR

### ISSUE THREAD

**Issue by starik1968** [RealRaven2000/SmartTemplates#296]
Hello, Smarttemplate is deactivated due to incompatibilty, what can I do?
Thanks in advance
cu
F. :-)

**Comment by RealRaven2000** [comment]
Release is in preparation - please get the latest version here #261 - please scroll down to the latest comment and follow instructions:

https://github.com/RealRaven2000/SmartTemplates/issues/261#issuecomment-2225370594

**Comment by RealRaven2000** [comment]
Implemented in 4.6 - published 14/07/2024
