### ISSUE TITLE
Define quote header from file - with relative path support

### ISSUE THREAD

**Issue by lpointal** [RealRaven2000/SmartTemplates#70]
Hello, I'm trying to share my templates between several PCs (with an OwnCloud sync) and install them inside reply-template selection menus.
How can I specify in a template to use some other¹  file as quote header before quote and template.

Thanks.
Laurent Pointal.

¹ relative path, as sync folder has not same path on all hosts)

**Comment by RealRaven2000** [comment]
One way to have different quote headers is to use different identities and store them this way. Unfortunately if you have quote headers defined in the Accounts section of ST4 they are always pulled in automatically. I think what we would need is a new variable to avoid this.

With Stationery we had a placeholder variable %quoteHeader% maybe we can re-use this and make it dependent on identity / have an option to omit it. The first implementation could be as simple as having:

```
%quoteHeader(none)%
```


to avoid pulling in the quote header - then you could just integrate the actual code in the external html template itself,

Further we could have:

```
%quoteHeader(email@address)%
```

- to pull in the quote header from a specific account setting.

**Comment by RealRaven2000** [comment]
> Hello, I'm trying to share my templates between several PCs (with an OwnCloud sync) and install them inside reply-template selection menus. How can I specify in a template to use some other¹ file as quote header before quote and template.
> 
> Thanks. Laurent Pointal.
> 
> ¹ relative path, as sync folder has not same path on all hosts)

the problem is - if you wanted to use `%file()%` with a relative path in the quote Header section (which was my first thought for solving this problem), neither SmartTemplates nor Thunderbird have a concept of where the root folder is. Maybe we should investigate a new global setting a root folder for anything written within the template + quote fields under Write, Reply and Forward?

**Comment by RealRaven2000** [comment]
Did the workaround work for you?

**Comment by lpointal** [comment]
Hello, I finally leave my pro templates in my pro PC and dont investigate in the workaround to have them on other hosts (via our NextCloud sync).
You can close the issue.
Thanks again for your replies.
