### ISSUE TITLE
`%sig(html)%` adds unnecessary/unwanted extra-space/paragraph at its end

### ISSUE THREAD

**Issue by setedivento** [RealRaven2000/SmartTemplates#80]
**OS:** Windows 10, build 2004
**Thunderbrid:** v. 68.11.0 (32 bit)

When composing a new message, if you select a template file like the one I am enclosing in here, the html signature is correctly added to the body, but an unnecessary/unwanted extra-paragraph is added at its end, too, like this:
`<p> </p>`

Please either remove this behaviour or, if it's an intended behaviour, add another parameter to the %sig% variable declaration signature, in order not to add this extra-paragraph at the end.

Also, I think this should not be an intended behaviour at all, for the very simple reason that if you need extra html, you can add it after the variable.

Thank you!

[template.zip](https://github.com/RealRaven2000/SmartTemplate4/files/5041241/template.zip)

**Comment by RealRaven2000** [comment]
Can you try unchecking the option "_Force Paragraph Mode_" in _global settings_:

![image](https://user-images.githubusercontent.com/6314674/89666749-d5cdfd80-d8d2-11ea-92aa-b28665709feb.png)

**Comment by setedivento** [comment]
First of all thanks for the prompt response.

I have tried that, but still an extra space character (e.g.: ' ') is added at the end:
when you use a block element in the html signature, such as <p>, or <div>, this causes the addition of an unwanted extra-line at the bottom of the mail.

Well, knowing that, one can use the setting you propose, and style the block element with a _display: inline;_
but the extra space addition remains something anomalous, in my point of view.

Anyway, thanks!

**Comment by RealRaven2000** [comment]
I will look at this stuff, once we have converted SmartTemplate4 to Thunderbird 78. Then if I don't check this in time, just send another comment here as a reminder - there are still a ton of other issues to work on as well - just check the open issues. Paragraph issues are actually sometimes harder to fix than one things - ST basically completely rips the Tb mail apart and rebuilds it from scratch over 10,000 lines of code. Very very complex stuff... But I will try to keep it in mind!

**Comment by RealRaven2000** [comment]
> First of all thanks for the prompt response.
> 
> I have tried that, but still an extra space character (e.g.: ' ') is added at the end:
> and when you use a block element in the html signature, such as `<p>`, or `<div>`, this causes the addition of an unwanted extra-line at the bottom of the mail.

I would like a good test case - my understanding is that signatures usually are in a block level element (e.g. `div` or `p`) but it sounds like SmartTemplates inserts a `<br>`? Note that if you use "Plain text" mode then any line breaks in your template (even at the end of it) will be converted to real line break - same as with the option [x] convert line breaks to `<br>` in HTML mode. generally I really dislike that option because it prevents you from writing readable markup. But an additional space character will never ever create an additional line break.

**Comment by setedivento** [comment]
OK, I'll rewrite the last use-case in steps, for better clarity.
By _the last use case_ I mean the one you just quoted, where I say _an extra space character is added at the end_.

1. make sure that, in Global Settings, the box "Force Paragraph Mode" is unchecked
2. open any e-mail account's settings, and set this signature (using html):
```html
<div id="justMySignature" style="font-weight:bold; color:red;">
  my signature
</div>
```
3. go to SmartTemplate, in "Account" select "Template files", then select the tab "New Messages"
4. add a new template using the html file provided in the zip above (template.zip), or the file enclosed in this post (blah blah.html)
5. now compose a new message for said e-mail account, using the template you just created

Result: an extra space character is created at the end, inside the div with id="smartTemplate4-template".

No <br> addition is involved here, but the extra unwanted space creates a sort of a new-line graphical effect: this is due to the div with id="justMySignature" being a block element.

Hope it's clearer now.

**Comment by RealRaven2000** [comment]
I tested your last example. So SmartTemplates inserts its own template in the form of a div:

```html
    <div id="smartTemplate4-template">blah blah
      <div id="tbDailySignature" style="width: 65%; border: 1px solid #00AAEE; background: linear-gradient(to bottom,
        #ace1f2 0%,#4cc6e8 50%,#3bbadd 51%,#57d0f1 100%); border-radius: 0.8em; color: #444;font:x-small verdana; color:
        #444;
        padding: 0.4em 1.2em 0.8em; margin-bottom: 1.5em; box-shadow: 5px 5px 3px rgba(80,120,180,0.4);">
        <span style="color: #0044AA; font-size: 14pt; font-family: &quot;Berlin Sans FB&quot;,Calibri,Arial,Sans-Serif;
          font-weight:normal; text-shadow: 1px 1px 1px rgba(150,150,190,0.8);text-transform: uppercase;line-height:
          1.4em;"><a href="mailto:thunderbirddaily@gmail.com">Thunderbird Daily-Addons</a></span><br>
        Thunderbird Addons Developer (<a
          href="https://addons.mozilla.org/thunderbird/addon/quickfolders-tabbed-folders/">QuickFolders</a>, <a
        AMO Editor<br>
        Visit my <a href="https://www.youtube.com/c/thunderbirddaily">YouTube Channel</a> for email tips and tricks <img
          style="margin-top: 1em; float: right; box-shadow: 1px 1px 2px rgba(20, 20, 20, 0.4);" moz-do-not-send="false"
          class="myLogo" src="data:image/png;..."
          alt="Get Thunderbird!" width="94" height="15">
      </div>
     </div>

```

the space character is in front of the last closing </div> I guess this is what you may see.  Note that the whole code is also indented by several tabs which would also collapse to a single white space...

**Comment by RealRaven2000** [comment]
I think I know what happens - when you do not use the %cursor% variable, SmartTemplates tries to expliticely set the cursor - it does this by temporarily inserting a tag `<span class="st4cursor">` according to composition settings (on top of the new mail or at the bottom before the quoted mail etc.). This is then replaced with a space for setting the cursor position. So if you are using %cursor% in your template instead this will put the space elsewhere.

The space can be disabled in General Settings, here:
![image](https://user-images.githubusercontent.com/6314674/152160991-209ba718-efcd-406b-bfda-d109e00d7bdd.png)
